### ISSUE TITLE
大佬 更新一下吧

### ISSUE THREAD

**Issue by ezrawic4j** [ggtony233/tweb-dockerfile#1]
rt

**Comment by ezrawic4j** [comment]
最好先本地测试一下，最新版的我编译老是出问题 用你的旧版本正常了，新版本老师刷不出来 二维码

**Comment by ggtony233** [comment]
之前由于网络原因，用的是gitee的镜像，最近由于gitee对免费用户大小做限制，无法更新到最新了
现在再试试呢？

**Comment by ggtony233** [comment]
> 最好先本地测试一下，最新版的我编译老是出问题 用你的旧版本正常了，新版本老师刷不出来 二维码

二维码加载不出来大概是你梯子寄了
